import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import '@/src/assets/styles/globals.css'
import UserSidebar from '@/src/components/sidebar/UserSidebar'
import { ThemeProvider } from '@/src/components/theme-provider'
import { SidebarProvider, SidebarTrigger } from '@/src/components/ui/sidebar'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Zorly',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
    >
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SidebarProvider>
          <UserSidebar />
          <SidebarTrigger />
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {children}
          </ThemeProvider>
        </SidebarProvider>
      </body>
    </html>
  )
}
